name: Bump Version on Main

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.10.0

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get PR number
        id: pr
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Run bump-semver.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x bump-semver.sh
          ./bump-semver.sh 